simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from accounts.views import SignUp,CreateProfile,DetailProfile,VerifyProfile
app_name= 'accounts'

urlpatterns = [
    url(r'^login/$',auth_views.LoginView.as_view(template_name= 'accounts/login.html'),name= 'login'),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name = 'logout'),
    url(r'^signup/$',SignUp.as_view(),name = 'signup'),
    url(r'^(?P<username>[-\w\d]+)/profile/create', CreateProfile.as_view(), name='createprofile'),
    url(r'^(?P<username>[-\w]+)/profile/(?P<pk>\d+)/', DetailProfile.as_view(), name='profile'),
    url(r'^(?P<username>[-\w]+)/profile/',VerifyProfile , name='verifyprofile'),
]

simplesocial/posts/urls.py
from django.conf.urls import url

from . import views
app_name = 'posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(), name='all'),
    url(r'new/$',views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(), name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(), name='delete'),
]

simplesocial/simplesocial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from .import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',views.TestPage.as_view(),name='test'),
    url(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups/',include('groups.urls',namespace='groups')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>SocialConnect</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

    <link href="{% static "simplesocial/css/master.css" %}" rel="stylesheet">

  </head>
  <body>


    <nav class='navbar mynav navbar-fixed-top' role ='navigation'  id ='navbar' >
      <div class="container">
        <a class ='navbar-brand mynav' href="{% url 'home' %}" style="color:white"> SocialConnect</a>

        <ul class ='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}" style="color:white">Post</a></li>
            <li><a href="{% url 'groups:all' %}" style="color:white">Groups</a></li>
            <li><a href="{% url 'groups:create' %}" style="color:white">Create Group</a></li>
            <li><a href="{% url 'accounts:verifyprofile' username=user.username  %}" style="color:white">Complete Profile</a></li>
            <li><a href="{% url 'accounts:logout' %}" style="color:white">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'groups:all' %}" style="color:white">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}" style="color:white">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}" style="color:white">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <br>
    <br>
    <br>
    <br>
    <br>


    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

  </body>
</html>

simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1> Welcome to SocialConnect </h1>
{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}

{% block content %}
  <h1> You are now logged in!</h1>


{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}

{% block content %}
  <h1>Thanks for visiting, come back soon!</h1>


{% endblock %}